---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/e57ee3bed7a6f73077a3f55a38e76e40ec87a7cf/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: endpoint-package-pipeline
  description: Buildkite Pipeline for endpoint-package
  links:
    - title: Endpoint Package Pipeline
      url: https://buildkite.com/elastic/endpoint-package

spec:
  type: buildkite-pipeline
  owner: group: security-defend-workflows
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: endpoint-package
    spec:
      repository: elastic/endpoint-package
      pipeline_file: ".buildkite/pipeline.yml.py"
      teams:
        endpoint-ci-admin: {}
        security-defend-workflows:
          access_level: BUILD_AND_READ
        everyone:
          access_level: READ_ONLY
