---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: buildkite-pipeline-endpoint-package
  description: Buildkite Pipeline for endpoint-package
  links:
    - title: Pipeline
      url: https://buildkite.com/elastic/endpoint-package

spec:
  type: buildkite-pipeline
  owner: group:security-defend-workflows
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: endpoint-package
    spec:
      repository: elastic/endpoint-package
      pipeline_file: ".buildkite/pipeline.yml"
      teams:
        # your-team:
        #  access_level: MANAGE_BUILD_AND_READ
        everyone:
          access_level: READ_ONLY
