# This should start the environment with the latest snapshots.

version: "3.8"
services:
  package-registry:
    # to use the latest package-registry alone you can use: docker.elastic.co/package-registry/package-registry:master
    environment:
      - EPR_FEATURE_PROXY_MODE=true
    image: docker.elastic.co/package-registry/package-registry:main
    volumes:
      - ./package-registry.config.yml:/package-registry/config.yml
      - ./out/packages:/packages/endpoint-package
    ports:
      - "127.0.0.1:8080:8080"
